module.exports = {
    spec: [
        './test/*.test.js',
        './test/**/*.test.js',
        './test/**/**/*.test.js',
        './test/**/**/**/*.test.js',
        './test/test.*.js',
        './test/**/test.*.js',
        './test/**/**/test.*.js',
        './test/**/**/**/test.*.js',
        './test/*.test.mjs',
        './test/**/*.test.mjs',
        './test/**/**/*.test.mjs',
        './test/**/**/**/*.test.mjs',
        './test/test.*.mjs',
        './test/**/test.*.mjs',
        './test/**/**/test.*.mjs',
        './test/**/**/**/test.*.mjs',
    ],
};